### ISSUE TITLE
Error with Latest Composer Update (bower-asset/summernote)

### ISSUE THREAD

**Issue by Stratigos** [zelenin/yii2-summernote-widget#5]
Today I recieved the following error while running composer update on my Yii2 project:

    [Composer\DependencyResolver\SolverProblemsException]                                                                                   
    Problem 1                                                                                                                             
      - Installation request for zelenin/yii2-summernote-widget dev-master -> satisfiable by zelenin/yii2-summernote-widget[dev-master].  
      - zelenin/yii2-summernote-widget dev-master requires bower-asset/summernote ~0.5@stable -> no matching package found.               
    Potential causes:                                                                                                                       
    - A typo in the package name                                                                                                           
    - The package is not available in a stable-enough version according to your minimum-stability setting                                  
    see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.                                        
    Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

I have my composer.json with the following entry in the 'require' section:

`"zelenin/yii2-summernote-widget": "dev-master"`

Do I need to add anything else to my composer.json to get past this issue?

**Comment by Stratigos** [comment]
Simply adding "bower-asset/summernote": "@stable", to the "require" section of my composer.json seems to have fixed this issue. 

This may seem obvious to others, but Im still getting used to the composer ecosystem :)

**Comment by zelenin** [comment]
yes, that's walkaround for this issue.
