### ISSUE TITLE
CodeMirror as a default option

### ISSUE THREAD

**Issue by bizley-code** [zelenin/yii2-summernote-widget#7]
Hi! Thanks for this widget - it is really useful.
I have one question about CodeMirror. Why is it set as default option? CM is great but not needed all the time. I know I can set 'codemirror' => null in options but there are many people that don't care about CM and they get additional 3MB of assets files.

**Comment by zelenin** [comment]
https://github.com/zelenin/yii2-summernote-widget/pull/2
